import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, FileText } from "lucide-react";
import { PageHeader } from "@/components/app-shell/page-header";
import { buttonVariants } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { getLoadByIdAction } from "@/lib/actions/loads";
import { formatCurrency, formatDateShort } from "@/lib/utils";
import { formatWeightKg, formatWeightTon } from "@/lib/domain/weights";
import { requireRole } from "@/lib/security/auth";
import { notFound } from "next/navigation";
export const metadata: Metadata = { title: "Detail muatan" };
export default async function LoadDetailPage({ params }: { params: Promise<{ id: string }> }) { await requireRole(["OWNER", "FINANCE"]); const { id } = await params; const load = await getLoadByIdAction(id); if (!load) notFound(); return <div className="space-y-6"><PageHeader title={load.loadNumber} description={`${formatDateShort(load.loadDate)} · ${load.destinationName}`}><Link href="/loads" className={buttonVariants({ variant: "outline", size: "sm" })}><ArrowLeft className="mr-1.5 size-4" />Daftar muatan</Link>{load.status === "DISPATCHED" && <Link href={`/loads/${load.id}/reconcile`} className={buttonVariants({ size: "sm" })}><CheckCircle2 className="mr-1.5 size-4" />Catat hasil pabrik</Link>}</PageHeader><div className="grid gap-3 min-[500px]:grid-cols-3"><div className="erp-surface p-4"><p className="text-xs text-muted-foreground">Total muatan</p><p className="mt-2 text-xl font-bold tabular-nums">{formatWeightKg(load.totalQuantityKg)}</p><p className="mt-1 text-xs text-muted-foreground">{formatWeightTon(load.totalQuantityKg)}</p></div><div className="erp-surface p-4"><p className="text-xs text-muted-foreground">Pembelian sumber</p><p className="mt-2 text-xl font-bold">{formatCurrency(load.totalPurchaseCost)}</p></div><div className="erp-surface p-4"><p className="text-xs text-muted-foreground">Status</p><Badge className="mt-3" variant={load.status === "RECONCILED" ? "default" : "secondary"}>{load.status === "RECONCILED" ? "Selesai" : load.status === "DISPATCHED" ? "Menunggu hasil pabrik" : load.status}</Badge></div></div><section className="erp-surface overflow-hidden"><div className="border-b border-border bg-muted/30 p-4"><h2 className="text-sm font-semibold">Rincian ikan</h2></div><div className="divide-y divide-border">{load.items.map((item) => <div key={item.id} className="grid gap-2 p-4 sm:grid-cols-[1fr_1fr_10rem_10rem] sm:items-center"><div><p className="text-sm font-semibold">{item.productName}{item.productSize ? ` [${item.productSize}]` : ""}</p><p className="mt-1 text-xs text-muted-foreground">Sumber: {item.sourceName}</p></div><p className="text-xs text-muted-foreground">Input {item.inputQuantity} {item.inputUnit.toLowerCase()}</p><p className="text-sm font-medium tabular-nums">{formatWeightKg(item.quantityKg)}</p><p className="text-sm font-semibold tabular-nums">{formatCurrency(item.purchaseTotal)}</p></div>)}</div></section><section className="erp-surface p-5"><div className="flex items-center gap-3"><FileText className="size-5 text-primary" /><div><p className="text-sm font-semibold">Invoice pabrik</p><p className="mt-1 text-xs text-muted-foreground">{load.invoiceNumber ?? "Nomor invoice belum tersedia"} · Dasar {load.invoiceBasis === "ACCEPTED" ? "berat diterima" : "berat berangkat"}</p></div></div></section></div>; }
